[package]
name = "RocksDict"
version = "0.3.0"
edition = "2021"
description = "Rocksdb Python Binding"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rocksdict"
crate-type = ["cdylib"]

[dependencies]
rocksdb = { git = "https://github.com/Congyuwang/rust-rocksdb", branch = "rocksdict" }
librocksdb-sys = { git = "https://github.com/Congyuwang/rust-rocksdb", branch = "rocksdict" }
ahash = "0.8.1"
num-bigint = "^0.4.3"
libc = "0.2.112"

[dependencies.pyo3]
version = "0.17.3"
features = ["extension-module", "num-bigint"]

[package.metadata.maturin]
python-source = "python"
