[package]
name = "RocksDict"
version = "0.2.10"
edition = "2021"
description = "On-disk Dict With RocksDB (dbm alternative)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rocksdict"
crate-type = ["cdylib"]

[dependencies]
# modified to make rocksdb::db::DBAccess trait public
rocksdb = { git = "https://github.com/Congyuwang/rust-rocksdb", branch = "rocksdict" }
librocksdb-sys = "=6.20.3"
ahash = "^0.7"
num-bigint = "^0.4.3"
libc = "0.2.112"

[dependencies.pyo3]
version = "~0.15"
features = ["extension-module", "num-bigint"]

[package.metadata.maturin]
python-source = "python"
